# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 624421fa1690ea8c0a9d16c3c21f72ba582ed3a6d914abf5703803042a18f459c0e527ad3d7afc732e65bd57e49534f61897d19c26e8cc77fca3325a114ea026

test:
  secret_key_base: 3d06443d3f98db8db69480e4f088f62e806e1db2d7035f52221b87c9e7456de7488dbd81a56e4f1ade761a39cc36468eed68a13885e7d799d20c18157b734811

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
